#!/usr/bin/env bash
name="audit"
version='3.1.1'
depends=""
description="servis yöneticisi"
source="https://github.com/linux-audit/audit-userspace/archive/refs/tags/v$version.tar.gz"
groups="sys.process"
setup()
{
	cp $PACKAGEDIR/auditd.initd /tmp/bps/build/auditd.initd
	cp $PACKAGEDIR/auditd.confd /tmp/bps/build/auditd.confd
	
	cd $SOURCEDIR
	 autoreconf -fv --install
	 cd $BUILDDIR
    ../${name}-${version}/configure --prefix=/usr \
        --sysconfdir=/etc \
        --libdir=/usr/lib64 \
        --disable-zos-remote \
        --disable-listener \
        --disable-systemd \
        --disable-gssapi-krb5 \
        --enable-shared=audit \
	    --with-arm \
	    --with-aarch64\
	    --without-python \
	    --without-python3 \
	    --with-libcap-ng=no 
		    
     
}
build()
{
	make
}
package()
{
	make install DESTDIR=$DESTDIR
	install -Dm755 ../auditd.initd "$DESTDIR"/etc/init.d/auditd
    	install -Dm755 ../auditd.confd "$DESTDIR"/etc/conf.d/auditd
}


