#!/usr/bin/env bash
version="13.1.0"
name="libgcc"
depends="glibc,gmp,mpfr,libmpc,zlib,libisl"
builddepend="flex,elfutils,curl,linux-headers"
description="DOS filesystem tools - provides mkdosfs, mkfs.msdos, mkfs.vfat"
source="https://ftp.gnu.org/gnu/gcc/gcc-${version}/gcc-${version}.tar.xz"
groups="sys.devel"

export CFLAGS="-O2 -s"
export CXXFLAGS="-O2 -s"
unset LDFLAGS
setup()
{
case $(uname -m) in
  x86_64)
    sed -i.orig '/m64=/s/lib64/lib/' gcc/config/i386/t-linux64
  ;;
esac

	 options=(
      --prefix=/usr
      --libexecdir=/usr/libexec
      --mandir=/usr/share/man
      --infodir=/usr/share/info
      --enable-languages=c,c++
      --with-linker-hash-style=gnu
      --with-system-zlib
      --enable-__cxa_atexit
      --enable-cet=auto
      --enable-checking=release
      --enable-clocale=gnu
      --enable-default-pie
      --enable-default-ssp
      --enable-gnu-indirect-function
      --enable-gnu-unique-object
      --enable-libstdcxx-backtrace
      --enable-link-serialization=1
      --enable-linker-build-id
      --enable-lto
      --disable-multilib
      --enable-plugin
      --enable-shared
      --enable-threads=posix
      --disable-libssp
      --disable-libstdcxx-pch
      --disable-werror
      --without-zstd
      --disable-nls
    )
    cd $SOURCEDIR
    mkdir build
    cd build
    ../configure ${options[@]} \
        --libdir=/usr/lib64 \
        --target=x86_64-pc-linux-gnu 

	
}
build()
{
	cd $SOURCEDIR/build
	make
}
package()
{
	cd $SOURCEDIR/build
	make install DESTDIR=${DESTDIR}
    	
    	mkdir -p ${DESTDIR}/usr/lib64/
    	ln -s gcc ${DESTDIR}/usr/bin/cc
    	ln -s g++ ${DESTDIR}/usr/bin/cxx
    	cd $DESTDIR
    	#find ./ -iname "*" -exec strip -s {} \;
    	 while read -rd '' file; do
        case "$(file -Sib "$file")" in
            application/x-executable\;*)     # Binaries
                strip "$file" ;;
            application/x-pie-executable\;*) # Relocatable binaries
                strip "$file" ;;
        esac
       
    done< <(find "./" -type f -iname "*" -print0)
    	 
}

yedek(){
 while read -rd '' file; do
        case "$(file -Sib "$file")" in
            application/x-sharedlib\;*)      # Libraries (.so)
                strip "$file" ;;
            application/x-executable\;*)     # Binaries
                strip "$file" ;;
            application/x-pie-executable\;*) # Relocatable binaries
                strip "$file" ;;
        esac
       
    done< <(find "./" -type f -iname "*" -print0)	

}

