#!/usr/bin/env bash
name="libmd"
version="1.1.0"
description="Message Digest functions from BSD systems"
depends=""
group="app.crypt"
source="https://archive.hadrons.org/software/libmd/libmd-$version.tar.xz"
setup(){
    ../${name}-${version}/configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make 
}

package(){
    make install DESTDIR=$DESTDIR
}

