#!/usr/bin/env bash
name="xz-utils"
version="5.4.5"
description="lzma compression utilities"
source="https://tukaani.org/xz/xz-${version}.tar.gz"
md5sums="66f82a9fa24623f5ea8a9ee6b4f808e2"
group="app.arch"


setup(){
    $SOURCEDIR/configure --prefix=/usr \
	--libdir=/usr/lib64 \
	--enable-static \
	--enable-shared \
	--enable-doc \
	--enable-nls
	#$(use_opt doc --enable-doc --disable-doc) \
	#$(use_opt nls --enable-nls --disable-nls)
}
build(){
    make $jobs
}
package(){
    make install DESTDIR=$DESTDIR
}
