#!/usr/bin/env bash
name="kernel-headers"
version="6.10.8"
description="Linux kernel headers"
source="https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-$version.tar.xz"
depends=""
builddepend="rsync,bc,cpio,gettext,elfutils,pahole,perl,python,tar,xz-utils"
group="sys.kernel"

setup(){

	cp -prvf $PACKAGEDIR/files/ /tmp/bps/build/
	cd $SOURCEDIR
	
	patch -Np1 -i ../files/patch-$version
	cp ../files/config .config
	make olddefconfig

}

build(){
	make headers 
}

package(){
	arch="x86"
	kernelbuilddir="${DESTDIR}/lib/modules/${version}/build"
	
	# install libc headers
	mkdir -p "$DESTDIR/usr/include/linux"
	cp -v -t "$DESTDIR/usr/include/" -a include/linux/
	cp -v -t "$DESTDIR/usr/" -a tools/include
	
	make headers_install INSTALL_HDR_PATH=$DESTDIR/usr
	
	# install headers
    	mkdir -p "$kernelbuilddir" "$kernelbuilddir/arch/$arch"
    	cp -v -t "$kernelbuilddir" -a include
   	cp -v -t "$kernelbuilddir/arch/$arch" -a arch/$arch/include
    	install -Dt "$kernelbuilddir/arch/$arch/kernel" -m644 arch/$arch/kernel/asm-offsets.*
    	install -Dt "$kernelbuilddir/drivers/md" -m644 drivers/md/*.h
    	install -Dt "$kernelbuilddir/net/mac80211" -m644 net/mac80211/*.h
    	install -Dt "$kernelbuilddir/drivers/media/i2c" -m644 drivers/media/i2c/msp3400-driver.h
    	install -Dt "$kernelbuilddir/drivers/media/usb/dvb-usb" -m644 drivers/media/usb/dvb-usb/*.h
    	install -Dt "$kernelbuilddir/drivers/media/dvb-frontends" -m644 drivers/media/dvb-frontends/*.h
    	install -Dt "$kernelbuilddir/drivers/media/tuners" -m644 drivers/media/tuners/*.h
    	# https://bugs.archlinux.org/task/71392
    	install -Dt "$kernelbuilddir/drivers/iio/common/hid-sensors" -m644 drivers/iio/common/hid-sensors/*.h

	find . -name 'Kconfig*' -exec install -Dm644 {} "$kernelbuilddir/{}" \;
	
	# clearing
	find -L "$kernelbuilddir" -type l -printf 'Removing %P\n' -delete
	find "$kernelbuilddir" -type f -name '*.o' -printf 'Removing %P\n' -delete

	
	echo "Adding symlink..."
	mkdir -p "$DESTDIR/usr/src"
	ln -sr "$kernelbuilddir" "$DESTDIR/usr/src/linux"

    
    #------------------------------
    mv -vf System.map $DESTDIR/boot/System.map-$version
    find "$DESTDIR"/usr/include/ ! -iname "*.h" -type f -exec rm -v {} \+

}
