#!/usr/bin/env bash
name="ext-lvm2"
version="2_03_21"
description="User-land utilities for LVM2 (device-mapper) software"
source="https://github.com/lvmteam/lvm2/archive/refs/tags/v$version.tar.gz"
depends="libaio"
builddepend=""
group="sys.fs"

setup(){
	cd $SOURCEDIR
	./configure --prefix=/usr \
		--libdir=/usr/lib64/  \
		CONFIG_SHELL=/bin/bash \
		--sbindir=/usr/bin \
		--sysconfdir=/etc \
		--localstatedir=/var \
		--enable-cmdlib \
		--enable-dmeventd \
		--enable-lvmpolld \
		--enable-pkgconfig \
		--enable-readline \
		--enable-udev_rules \
		--enable-udev_sync \
		--enable-write_install \
		--disable-systemd \
		--with-cache=internal \
		--with-default-dm-run-dir=/run \
		--with-default-locking-dir=/run/lock/lvm \
		--with-default-pid-dir=/run \
		--with-default-run-dir=/run/lvm \
		--with-thin=internal \
		--with-udev-prefix=/usr
}

build(){
    make
}

package() {
    make install DESTDIR=$DESTDIR
}


