#!/usr/bin/env bash
version="1.3-20230209"
name="dialog"
depends="glibc,readline,ncurses"
description="shell box kütüphanesi"
source="https://invisible-island.net/archives/dialog/${name}-${version}.tgz"
groups="sys.apps"
setup()
{
	../${name}-${version}/configure --prefix=/usr \
         --libdir=/lib64/ \
         --with-ncursesw
    # change default color blue to red
    cd $SOURCEDIR
  #  sed -i "s/COLOR_BLUE/COLOR_RED/g" dlg_colors.h
  #  sed -i "s/COLOR_CYAN/COLOR_MAGENTA/g" dlg_colors.h
	
}
build()
{
	cd $BUILDDIR
	make 
}
package()
{
	make install DESTDIR=$DESTDIR
}


