#!/usr/bin/env bash
version="0.8.3"
name="libcap-ng"
depends="glibc,acl,openssl,libtool"
description="shell ve network copy"
source="https://github.com/stevegrubb/libcap-ng/archive/refs/tags/v${version}.zip"
groups="sys.libs"
setup()
{	
	cd $SOURCEDIR
	autoreconf -fvi
	cd $BUILDDIR
	../${name}-${version}/configure --prefix=/usr \
	  --libdir=/lib64 \
	  $(use_opt python --with-python --without-python) \
        $(use_opt python --with-python3 --without-python3)
	
}
build()
{
	make 
}
package()
{
	make install DESTDIR=$DESTDIR
}


