#!/usr/bin/env bash
name="efivar"
version="39"
description="Tools and libraries to work with EFI variables"
source="https://github.com/rhboot/efivar/archive/refs/tags/$version.tar.gz"
depends=""
builddepend=""
group="sys.libs"

setup(){
	export ERRORS=''
	export PATH=$PATH:$HOME
	# fake mandoc for ignore extra dependency
    echo "exit 0" > $HOME/mandoc
    chmod +x $HOME/mandoc
}

build(){
	cd $SOURCEDIR
    make
}

package(){
	local make_options=(
    V=1
    libdir=/usr/lib64/
    bindir=/usr/bin/
    mandir=/usr/share/man/
    includedir=/usr/include/
	)
    make DESTDIR=$DESTDIR "${make_options[@]}" install
}


