#!/usr/bin/env bash
version="1.36.1"
name="busybox"
depends="glibc"
description="minimal linux araç paketi static derlenmiş hali"
source="https://busybox.net/downloads/${name}-${version}.tar.bz2"
group="sys.base"
setup()
{
	cp -prfv $PACKAGEDIR/files /tmp/bps/build/

	cd $SOURCEDIR
	make defconfig
	sed -i "s|.*CONFIG_STATIC_LIBGCC .*|CONFIG_STATIC_LIBGCC=y|" .config
	sed -i "s|.*CONFIG_STATIC .*|CONFIG_STATIC=y|" .config
}
build()
{

	make 
}
package()
{
	mkdir -p $DESTDIR/bin
	install busybox ${DESTDIR}/bin/busybox
	# install udhcpc script and service
 mkdir -p ${DESTDIR}/usr/share/udhcpc/ ${DESTDIR}/etc/init.d/
    install ../files/udhcpc.script ${DESTDIR}/usr/share/udhcpc/default.script
    install ../files/udhcpc.openrc ${DESTDIR}/etc/init.d/udhcpc
}


