#!/usr/bin/env bash
name="libssh"
version="0.10.4"
description="C library implenting the SSHv2 protocol on client and server side"
source=("https://www.libssh.org/files/0.10/libssh-${version}.tar.xz")
group="net.libs"
depends="openssl,zlib"


setup() {
    cmake -S $SOURCEDIR -B $BUILDDIR \
	-DCMAKE_INSTALL_PREFIX=/usr \
	-DCMAKE_INSTALL_LIBDIR=/usr/lib64 \
	-DWITH_EXAMPLES=NO \
	-DBUILD_SHARED_LIBS=YES \
	-DBUILD_STATIC_LIB=YES \
	-DWITH_NACL=OFF \
	-DWITH_GCRYPT=OFF \
	-DWITH_MBEDTLS=OFF \
	-DWITH_GSSAPI=OFF \
	-DWITH_PCAP=OFF \
	-DWITH_SERVER=ON \
	-DWITH_SFTP=ON \
	-DWITH_ZLIB=ON
}
build() {
    make -C $BUILDDIR
}
package() {
    make -C $BUILDDIR install DESTDIR=$DESTDIR
    install $BUILDDIR/src/libssh.a ${DESTDIR}/usr/lib64/
}
