#!/usr/bin/env bash
name="openssh"
version="9.6p1"
description="OpenBSD ssh server & client"
source="https://ftp.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-$version.tar.gz"
depends="zlib,libxcrypt,openssl,libmd,libssh"
        
group="net.misc"

setup(){
	cp -prfv $dizin/$paket/sshd.initd $BUILDDIR/
	cp -prfv $dizin/$paket/sshd.confd $BUILDDIR/
	cd $BUILDDIR
    ../${name}-${version}/configure --prefix=/usr \
        --libdir=/usr/lib64/ \
        --sysconfdir=/etc/ssh \
        --without-pam \
        --disable-strip \
        --with-ssl-engine \
        --with-privsep-user=nobody \
        --with-pid-dir=/run \
        --with-default-path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
}

build(){
    make
}

package(){
cd $BUILDDIR
    make install DESTDIR=$DESTDIR
    mkdir -p "$DESTDIR"/etc/{passwd,group,sysconf,init,conf}.d
    install -m755 -D sshd.initd "$DESTDIR"/etc/init.d/sshd
    install -m755 -D sshd.confd "$DESTDIR"/etc/conf.d/sshd
}

