#!/usr/bin/env bash
version="8.4.0"
name="curl"
depends="glibc,acl,openssl"
description="shell ve network copy"
source="https://curl.se/download/${name}-${version}.tar.xz"
groups="net.misc"
setup()
{
	opts=(
        --prefix=/usr
        --libdir=/usr/lib64
        --disable-ldap
        --disable-ldaps
        --disable-versioned-symbols
        --enable-doh
        --enable-ftp
        --enable-ipv6
        --with-ca-path=/etc/ssl/certs
        --with-ca-bundle=/etc/ssl/cert.pem
        --enable-threaded-resolverl
        --enable-websockets
        #$(use_opt zstd --with-zstd --without-zstd)
        #$(use_opt zlib --with-zlib --without-zlib)
        #$(use_opt brotli --with-brotli --without-brotli)
        #$(use_opt libssh --with-libssh --without-libssh)
        #$(use_opt libidn2 --with-libidn2 --without-libidn2)
    )
    
	cd $SOURCEDIR
	./configure ${opts[@]} --with-openssl

	
}
build()
{
	make 
}
package()
{
	make install DESTDIR=$DESTDIR
	cd $DESTDIR
	for ver in 3 4.0.0 4.1.0 4.2.0 4.3.0 4.4.0 4.5.0 4.6.0 4.7.0; do
        ln -s $DESTDIR/lib/libcurl.so.4.8.0 $DESTDIR/lib/libcurl.so.${ver}
    done
}


