#!/usr/bin/env bash
name="shadow"
version="4.13"
description="Password and account management tool suite with support for shadow files and PAM"
source="https://github.com/shadow-maint/shadow/releases/download/$version/shadow-$version.tar.xz"
depends="pam,libxcrypt,acl,attr"
group="sys.apps"

setup(){
	mkdir -p /tmp/bps/build/files
	cp -prvf $PACKAGEDIR/files/ /tmp/bps/build/
	cd $SOURCEDIR
	autoreconf -fiv      
        ./configure --prefix=/usr \
        --libdir=/usr/lib64 \
        --sysconfdir=/etc \
        --bindir=/usr/bin \
        --sbindir=/usr/sbin \
        --disable-account-tools-setuid \
        --without-sssd \
        --with-fcaps \
        --with-libpam \
        --without-group-name-max-length \
        --with-bcrypt \
        --with-yescrypt \
        --without-selinux
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
    # remove selinux stuff
    mkdir -p "${DESTDIR}/etc/default/"
    sed -i "/.*selinux.*/d" ${DESTDIR}/etc/pam.d/*
    install -vDm 600 ../files/useradd.defaults "${DESTDIR}/etc/default/useradd"
    install -vDm 600 ../files/system-auth "${DESTDIR}/etc/pam.d/system-auth"
}

